title: "Arjun Neervannan"
description: "Quant Researcher — projects, portfolio, and blog"
theme: jekyll-theme-minimal   # GitHub Pages–supported theme
show_downloads: false
github:
  is_project_page: false
  is_user_page: true
